# Setup
title:        DeLTA
tagline:      Deep Learning for aerospace applications
logo:         images/delta_white_noname.svg
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Alexandre Boulch
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
